In [1]:
import numpy as np
import pandas as pd


### 1. Define a dataset with 10000 random numbers drawn from a normal distribution with a mean
### of 100 and standard deviation of 10 and call it ‘Input_Data’. Use seed number of 10. Print
### mean and standard deviation of this vector. (2 points)

In [2]:
seed = 10
np.random.seed(seed)
Input_Data = np.random.normal(100,10,10000)

print("mean:",np.mean(Input_Data),"std:",np.std(Input_Data))

mean: 100.05102056001915 std: 9.89664012771695


### 2. Outlier detection: A common cut-off value in practice for finding outliers in a normal or
### normal-like distribution is three standard deviations from mean. Use this cut-off value to
### find the outliers in Input_Data. Create a new array of this outlier values named as ‘outliers’.
### Create another array that includes all the data except the outliers and name it as
### ‘outliers_removed’. Print the number of identified outliers and non-outlier data. (4 points)

In [3]:
Outliers = Input_Data[(Input_Data > 130) | (Input_Data < 70)]
Outliers

array([ 67.95598656,  66.82330948,  68.87355056, 136.09160707,
       134.54844984,  66.27652989,  66.06891386, 131.93371103,
       131.77053404, 131.58873021, 130.77067912, 131.42284866,
        63.78361204, 130.27240129,  66.96448475,  67.85970289,
       135.61219348, 136.9148933 , 132.86370446, 135.03308591])

In [4]:
Outliers_Removed = Input_Data[(Input_Data <= 130) & (Input_Data >= 70)]
Outliers_Removed

array([113.31586504, 107.15278974,  84.54599708, ..., 106.47377813,
       112.50739219, 111.629442  ])

In [5]:
print("Outliers:",len(Outliers),"Non-Outliers:",len(Outliers_Removed))

Outliers: 20 Non-Outliers: 9980


### 3. Create a 8´10 matrix of random integer numbers in the range of 1 to 100 and name it as
### ‘Raw_Data’ (4 points):
### a. Normalize all columns of Raw_Data by subtracting the column mean and divide by
### standard deviation and call this matrix ‘Normalized_Data1’. Print this matrix.
### b. Range all columns of Raw_Data such that the minimum value in each column is 0 and
### max is 1 and call this matrix ‘Normalized_Data1’. Print this matrix.

In [6]:
seed = 10
np.random.seed(seed)
x = np.random.randint(1,100,80)
Raw_Data = x.reshape(8,10)
Raw_Data

array([[10, 16, 65, 29, 90, 94, 30,  9, 74,  1],
       [41, 37, 17, 12, 55, 89, 63, 34, 73, 79],
       [50, 52, 55, 78, 70, 14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66, 32, 58, 37, 28, 19],
       [94, 78, 23, 24, 95, 12, 29, 75, 89, 10],
       [16, 19, 81, 72, 89, 12, 18, 47,  8, 76],
       [29, 34, 85, 97, 89, 45,  6,  5, 72, 89],
       [89, 51, 55, 35, 16, 78, 89, 16,  7, 86]])

In [7]:
# a. Normalize all columns of Raw_Data by subtracting the column mean and divide by
# standard deviation and call this matrix ‘Normalized_Data1’. Print this matrix.
Normalized_Data1 = np.zeros((8,10))
for i in range (10):
    Normalized_Data1[:,i] = (Raw_Data[:,i] - np.mean(Raw_Data[:,i]))/np.std(Raw_Data[:,i])

Normalized_Data1

array([[-1.19210473, -1.25797474,  0.23912114, -0.52494297,  0.75827238,
         1.42506053, -0.38326491, -0.93462296,  0.55735281, -1.52277335],
       [-0.13624054, -0.14566023, -1.63480779, -1.08269488, -0.6571694 ,
         1.27345835,  0.89751909,  0.19825335,  0.52722564,  0.64171542],
       [ 0.17030068,  0.64885013, -0.15128072,  1.08269488, -0.05055149,
        -1.00057442, -0.53851145, -0.70804769,  1.12976922,  0.86371427],
       [-0.47684189, -0.46346438,  1.21512579, -1.04988594, -0.21231627,
        -0.45480655,  0.70346091,  0.33419851, -0.82849743, -1.02327594],
       [ 1.66894662,  2.02600142, -1.40056667, -0.68898765,  0.96047835,
        -1.06121529, -0.42207655,  2.0561705 ,  1.0092605 , -1.27302464],
       [-0.98774392, -1.09907266,  0.86376412,  0.88584127,  0.71783119,
        -1.06121529, -0.84900455,  0.78734904, -1.43104101,  0.55846585],
       [-0.54496216, -0.3045623 ,  1.01992486,  1.70606466,  0.71783119,
        -0.06064087, -1.31474418, -1.11588317

In [8]:
# b. Range all columns of Raw_Data such that the minimum value in each column is 0 and
# max is 1 and call this matrix ‘Normalized_Data1’. Print this matrix.

Normalized_Data2 = np.zeros((8,10))
for i in range (10):
    Normalized_Data2[:,i] = (Raw_Data[:,i] - np.min(Raw_Data[:,i]))/(np.max(Raw_Data[:,i])-np.min(Raw_Data[:,i]))

Normalized_Data2

array([[0.        , 0.        , 0.65753425, 0.2       , 0.93670886,
        1.        , 0.28915663, 0.05714286, 0.77906977, 0.        ],
       [0.36904762, 0.33870968, 0.        , 0.        , 0.49367089,
        0.93902439, 0.68674699, 0.41428571, 0.76744186, 0.88636364],
       [0.47619048, 0.58064516, 0.52054795, 0.77647059, 0.6835443 ,
        0.02439024, 0.24096386, 0.12857143, 1.        , 0.97727273],
       [0.25      , 0.24193548, 1.        , 0.01176471, 0.63291139,
        0.24390244, 0.62650602, 0.45714286, 0.24418605, 0.20454545],
       [1.        , 1.        , 0.08219178, 0.14117647, 1.        ,
        0.        , 0.27710843, 1.        , 0.95348837, 0.10227273],
       [0.07142857, 0.0483871 , 0.87671233, 0.70588235, 0.92405063,
        0.        , 0.14457831, 0.6       , 0.01162791, 0.85227273],
       [0.22619048, 0.29032258, 0.93150685, 1.        , 0.92405063,
        0.40243902, 0.        , 0.        , 0.75581395, 1.        ],
       [0.94047619, 0.56451613, 0.5205479